<?php
/**
 * @file
 * Code for the Faculty publication feature.
 */

include_once 'faculty_publication.features.inc';

/**
 * Implements hook_entity_view().
 */
function faculty_publication_entity_view($entity, $type, $view_mode, $langcode) {

	// Add publicationid (from property table).
	if ($type == 'publication') {
		$entity->content['publication_id'] = array(
			'#markup' => t('Publication id from json: ') . $entity->publicationid,
			'#weight' => 10,
			//'#theme' => 'mymodule_my_additional_field',
		);
	}

}
