<?php
/**
 * @file
 * Drupal needs this blank file.
 */

// Prevent error with drush migrate commands when import users and contents.
define('FACULTY_MIGRATE_BASE_URL', 'http://faculty.dev');

define('FACULTY_MIGRATE_CATEGORY_SOURCE_ID', '@code');
define('FACULTY_MIGRATE_CATEGORY_PLURAL_KEY_ENTRY', 'categories');
define('FACULTY_MIGRATE_CATEGORY_SINGULAR_KEY_ENTRY', 'categorie');

define('FACULTY_MIGRATE_DEPTPED_SOURCE_ID', '@code');
define('FACULTY_MIGRATE_DEPTPED_VOC_MACHINE_NAME', 'deptped');
define('FACULTY_MIGRATE_DEPTPED_PLURAL_KEY_ENTRY', 'deptpeds');
define('FACULTY_MIGRATE_DEPTPED_SINGULAR_KEY_ENTRY', 'deptped');

define('FACULTY_MIGRATE_PROFESSOR_PLURAL_KEY_ENTRY', 'professors');
define('FACULTY_MIGRATE_PROFESSOR_SINGULAR_KEY_ENTRY', 'professor');
define('FACULTY_MIGRATE_PROFESSOR_DETAIL_SINGULAR_KEY_ENTRY', 'prof');
define('FACULTY_MIGRATE_USER_SOURCE_ID', '@profid');
define('FACULTY_MIGRATE_PROFESSOR_PROFILE_MACHINE_NAME', 'professor');
define('FACULTY_MIGRATE_PROFESSOR_DETAIL_PROFILE_MACHINE_NAME', 'professor_detail');

define('FACULTY_MIGRATE_PUBLICATION_SOURCE_ID', 'publicationid');
define('FACULTY_MIGRATE_NODE_BOOK_MACHINE_NAME', 'book');
define('FACULTY_MIGRATE_NODE_CASE_STUDY_MACHINE_NAME', 'case_study');
